/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface XlayersUpload {}
  interface XlayersViewer {}
  interface XlayersViewerCanvas {
    'data': SketchMSData;
  }
  interface XlayersViewerContainer {
    'data': SketchMSData;
  }
  interface XlayersViewerLayer {
    'data': SketchMSData;
    'layer': SketchMSLayer;
    'level': number;
    'wireframe': boolean;
  }
  interface XlayersViewerPage {
    'data': SketchMSData;
    'level': number;
    'page': SketchMSPage;
    'wireframe': boolean;
  }
}

declare global {


  interface HTMLXlayersUploadElement extends Components.XlayersUpload, HTMLStencilElement {}
  var HTMLXlayersUploadElement: {
    prototype: HTMLXlayersUploadElement;
    new (): HTMLXlayersUploadElement;
  };

  interface HTMLXlayersViewerElement extends Components.XlayersViewer, HTMLStencilElement {}
  var HTMLXlayersViewerElement: {
    prototype: HTMLXlayersViewerElement;
    new (): HTMLXlayersViewerElement;
  };

  interface HTMLXlayersViewerCanvasElement extends Components.XlayersViewerCanvas, HTMLStencilElement {}
  var HTMLXlayersViewerCanvasElement: {
    prototype: HTMLXlayersViewerCanvasElement;
    new (): HTMLXlayersViewerCanvasElement;
  };

  interface HTMLXlayersViewerContainerElement extends Components.XlayersViewerContainer, HTMLStencilElement {}
  var HTMLXlayersViewerContainerElement: {
    prototype: HTMLXlayersViewerContainerElement;
    new (): HTMLXlayersViewerContainerElement;
  };

  interface HTMLXlayersViewerLayerElement extends Components.XlayersViewerLayer, HTMLStencilElement {}
  var HTMLXlayersViewerLayerElement: {
    prototype: HTMLXlayersViewerLayerElement;
    new (): HTMLXlayersViewerLayerElement;
  };

  interface HTMLXlayersViewerPageElement extends Components.XlayersViewerPage, HTMLStencilElement {}
  var HTMLXlayersViewerPageElement: {
    prototype: HTMLXlayersViewerPageElement;
    new (): HTMLXlayersViewerPageElement;
  };
  interface HTMLElementTagNameMap {
    'xlayers-upload': HTMLXlayersUploadElement;
    'xlayers-viewer': HTMLXlayersViewerElement;
    'xlayers-viewer-canvas': HTMLXlayersViewerCanvasElement;
    'xlayers-viewer-container': HTMLXlayersViewerContainerElement;
    'xlayers-viewer-layer': HTMLXlayersViewerLayerElement;
    'xlayers-viewer-page': HTMLXlayersViewerPageElement;
  }
}

declare namespace LocalJSX {
  interface XlayersUpload extends JSXBase.HTMLAttributes<HTMLXlayersUploadElement> {
    'onFileUploaded'?: (event: CustomEvent<any>) => void;
  }
  interface XlayersViewer extends JSXBase.HTMLAttributes<HTMLXlayersViewerElement> {}
  interface XlayersViewerCanvas extends JSXBase.HTMLAttributes<HTMLXlayersViewerCanvasElement> {
    'data'?: SketchMSData;
  }
  interface XlayersViewerContainer extends JSXBase.HTMLAttributes<HTMLXlayersViewerContainerElement> {
    'data'?: SketchMSData;
  }
  interface XlayersViewerLayer extends JSXBase.HTMLAttributes<HTMLXlayersViewerLayerElement> {
    'data'?: SketchMSData;
    'layer'?: SketchMSLayer;
    'level'?: number;
    'wireframe'?: boolean;
  }
  interface XlayersViewerPage extends JSXBase.HTMLAttributes<HTMLXlayersViewerPageElement> {
    'data'?: SketchMSData;
    'level'?: number;
    'page'?: SketchMSPage;
    'wireframe'?: boolean;
  }

  interface IntrinsicElements {
    'xlayers-upload': XlayersUpload;
    'xlayers-viewer': XlayersViewer;
    'xlayers-viewer-canvas': XlayersViewerCanvas;
    'xlayers-viewer-container': XlayersViewerContainer;
    'xlayers-viewer-layer': XlayersViewerLayer;
    'xlayers-viewer-page': XlayersViewerPage;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


