name: xLayers-lite CI
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Dependencies
        run: npm install

      - name: Start xvfb
        if: startsWith(matrix.os, 'ubuntu')
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Run compile
        env:
          DISPLAY: ":99.0"
        run: npm build
      - name: Run tests
        env:
          DISPLAY: ":99.0"
        run: npm test
